path: src/assistants/analyst/
name: AnalystAssistant
available_functions:
  fire_weather_index:
    description: "Input latitude and longitude to receive decade-level FWI projection data, including historical (1995 - 2004), mid-century (2045 - 2054), and end-of-century projections (2085 - 2094)."
    parameters:
      lat:
        description: "The latitude of the location"
        type: number
      lon:
        description: "The longitude of the location"
        type: number
    required: ["lat", "lon"]
    appendix: "FWI.md"

  long_term_fire_history_records:
    description: "Provide latitude and longitude to get the three closest fire history records within a 36 km radius, dating back centuries. This is useful for understanding the long-term history of wildfires in the area and how they have changed over time."
    parameters:
      lat:
        description: "The latitude of the location"
        type: number
      lon:
        description: "The longitude of the location"
        type: number
    required: ["lat", "lon"]
    appendix: history.md

  recent_fire_incident_data:
    description: "To provide summary statistics of recent wildfire incidents (year 2015 - 2023) within 36 km of the specified area and time frame."
    parameters:
      lat:
        description: "The latitude of the location"
        type: number
      lon:
        description: "The longitude of the location"
        type: number
      start_year:
        description: "The start year of the historical data, must be later than 2015"
        type: number
      end_year:
        description: "The end year of the historical data, must be earlier than 2023"
        type: number
    required: ["lat", "lon", "start_year", "end_year"]
    appendix: incident.md
  
  literature_search:
    description: "Input a query related to the user's project or concern, and receive titles and abstracts of relevant papers."
    parameters:
      query:
        description: "A detailed query to search for based on the user's project. Please be as specific as possible. **Example:**\n- Effective wildfire mitigation techniques for forest ecosystems in Southern Kansas.\n- Fire-resistant construction materials and techniques for bridge building in wildfire-prone areas of Southern California.\n -Study of local vegetation types in Northern New Mexico and their influence on wildfire behavior and spread.\n"
        type: string
    required: ["query"]
    appendix: literature.md
  
  census:
    description: "Input a location to receive demographic information from the most recent census data."
    parameters:
      lat:
        description: "The latitude of the location"
        type: number
      lon:
        description: "The longitude of the location"
        type: number
    required: ["lat", "lon"]
    appendix: census.md

instructions: |
  As an expert consultant specializing in wildfire risks, your role is to assist your client with various aspects of wildfire and climate change understanding and mitigation. Effectively engage with your client in order to address their concerns. 

  Here is the information about your client:
  


init_message: |
  While I am preparing the analysis, I'd like to let you know that I can also report some census data. Specifically, I can analyze the following demographic information reported at the census block level within a 36 km radius of the location of interest:
  - Total population
  - Number of Housing Units
  - Number of People Below Poverty Level

  If you need to assess the potential impact of a wildfire on the local community, you can ask me to provide this demographic information by asking questions like: "who will be affected by the wildfire?"